### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by slavakurilyak** [mayt/BrowserGPT#27]
By default, [playwright](https://github.com/microsoft/playwright) by @microsoft operates in headless mode. This means that when you run automated tests or scripts using Playwright, it launches the browser in the background without displaying the graphical user interface. What does that mean? Headless mode is faster!

If we remove the `headless: false` flag, BrowserGPT unlocks new use cases for browser automation. 

For example:

```js
const browser = await chromium.launch({headless: true});
```

Respond with 👍 to collect community votes.

**Comment by BaseInfinity** [comment]
I don't see why we can't add another CLI argument to enable headless mode.

The problem though is sometimes an action will be executed but sort of silently fail and you wont see it if the browser is closed so you won't know what step you're on.

Though maybe with `AutoGPT` enabled it could self correct itself and headless mode would be more useful.

**Comment by slavakurilyak** [comment]
> The problem though is sometimes an action will be executed but sort of silently fail and you wont see it if the browser is closed so you won't know what step you're on.

Great idea! I made this into an issue here: https://github.com/mayt/BrowserGPT/issues/28

**Comment by mayt** [comment]
Would you be thinking of something like this? iterm2 allows you to embed images directly into the terminal so you can see what's going on in more detail without a headed browser. 

<img width="801" alt="Screenshot 2024-01-05 at 15 16 32" src="https://github.com/mayt/BrowserGPT/assets/326192/911c03d1-72ff-42ef-ab43-a71be414cce6">

**Comment by slavakurilyak** [comment]
Imagine the user starts with a prompt and BrowserGPT responds with a plan (see [Plan and Solve Prompting](https://arxiv.org/abs/2305.04091)). 

Example plan:

1. Visit website
2. Extract or scrape data
3. Store data into CSV

What's the ultimate use case of headless mode? Full automation. For headless mode to be fully autonomous, it needs to run without user intervention (no human-in-the-loop). For headless mode, I'm describing agent-like browser automation. Once the agent is done, tracing or logging can reveal progress and chain-of-thought reasoning which includes screenshots of the intermediate steps.

**Comment by BaseInfinity** [comment]
I have to read the complete responses but holy cow I love embedding images for headless mode in iterm2
