### ISSUE TITLE
Install no longer possible?

### ISSUE THREAD

**Issue by patrick-hilo** [mayt/BrowserGPT#31]
BrowserGPT can no longer be installed as https://nexus.corp.indeed.com/repository/npm is no longer reachable.

npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://nexus.corp.indeed.com/repository/npm/tmp/-/tmp-0.2.1.tgz failed, reason: getaddrinfo ENOTFOUND nexus.corp.indeed.com
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by mayt** [comment]
This should be fixed. Please try the latest master

**Comment by patrick-hilo** [comment]
thank you! I can confirm that one can install and start it again.
